"""
conftest.py — Shared fixtures for ConstructOS backend tests.

Run all tests:
    cd backend && pytest tests/ -v

Run one module:
    pytest tests/test_documents.py -v

Run with print output:
    pytest tests/ -v -s
"""
import os
import sys
import tempfile
import pytest
from fastapi.testclient import TestClient

# Make sure backend package is importable
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

# Point storage to temp dirs so tests never touch production data
_test_tmp = os.path.join(tempfile.gettempdir(), "constructos_test")
os.makedirs(_test_tmp, exist_ok=True)

os.environ["CHROMA_PATH"]    = os.path.join(_test_tmp, "chroma")
os.environ["UPLOAD_PATH"]    = os.path.join(_test_tmp, "uploads")
os.environ["PAGES_PATH"]     = os.path.join(_test_tmp, "pages")
os.environ["GEMINI_API_KEY"] = os.environ.get("GEMINI_API_KEY", "test-key")

from main import app

# ── Test PDF paths (generated by create_test_pdfs.py) ─────────────────────
_TEST_PDF_DIR = os.path.join(os.path.dirname(__file__), "test_pdfs")

SPEC_PDF      = os.path.join(_TEST_PDF_DIR, "spec.pdf")
BLUEPRINT_PDF = os.path.join(_TEST_PDF_DIR, "blueprint.pdf")
TINY_PDF      = os.path.join(_TEST_PDF_DIR, "tiny.pdf")
FAKE_TXT      = os.path.join(_TEST_PDF_DIR, "fake.txt")


@pytest.fixture(scope="session")
def client():
    """FastAPI TestClient — shared across entire test session."""
    with TestClient(app) as c:
        yield c


@pytest.fixture(scope="session")
def uploaded_spec(client):
    """Upload spec.pdf once and return its DocumentMeta. Used by multiple tests."""
    with open(SPEC_PDF, "rb") as f:
        res = client.post("/api/documents/upload",
                          files={"file": ("spec.pdf", f, "application/pdf")})
    assert res.status_code == 200, f"Spec upload failed: {res.text}"
    return res.json()


@pytest.fixture(scope="session")
def uploaded_blueprint(client):
    """Upload blueprint.pdf once and return its DocumentMeta."""
    with open(BLUEPRINT_PDF, "rb") as f:
        res = client.post("/api/documents/upload",
                          files={"file": ("blueprint.pdf", f, "application/pdf")})
    assert res.status_code == 200, f"Blueprint upload failed: {res.text}"
    return res.json()